name: "Find and Replace"
description: "Find and replace a string in your project files"
author: "Nithin Vasishta" inspired by "Jacob Tomlinson"
inputs:
  include:
    description: "A glob of files to include in our find and replace"
    default: "**" # Include everything by default
    required: false
  exclude:
    description: "A glob of files to exclude in our find and replace"
    default: ".git/**" # Ignore the `.git` directory by default
    required: false
  find:
    description: "The regular expression (or fixed string) we want to replace"
    required: true
  replace:
    description: "The new string to replace with"
    required: true
outputs:
  modifiedFiles:
    description: "The number of files which have been modified"
runs:
  using: "node16"
  image: "index.js"
